
class Constants:
    COMMAND_START_DIAL = "ATD"
    COMMAND_CHECK_SIGNAL_STATUS = "AT+CSQ"
    COMMAND_CHECK_NETWORK = "AT+COPS?"
    COMMAND_SEND_USSD = ""
    COMMAND_HANGUP_CALL = "ATH"
    COMMAND_GET_REG_STATUS = "AT+CREG?"
    OK_SIGNAL = "OK"
    WIN_SYS = 1
    LINUX_SYS = -1
    DARWIN_SYS = 0
    MAX_CONTACTS = 2000
    MAX_SMS_CHARS = 255
    MAX_SMS_MESSAGES = 1000
